---
- name: Create a directory if it does not exist
  hosts: all
  become: yes
  vars:
    path: /home/admin01/
    path1: /home/admin01/yogesh
  tasks:
    - name: Creating an empty directory
      ansible.builtin.file:
        path: "{{path}}/yogesh"
        state: directory
        mode: "0777"
    - name: Creating an empty file under created directory
      ansible.builtin.file:
        path: "{{path1}}/Advik"
        state: touch
        mode: "0777"
